[tools]
rojo = { source = "rojo-rbx/rojo", version = "6.2.0" }
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
wally = { source = "upliftgames/wally", version = "0.3.1" }
stylua = { source = "johnnymorganz/stylua", version = "0.11.2" }
